// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtlhj7NbTvcJMEM5qA5fnFiA1NoSYM_mc',
    appId: '1:156767151896:web:1a9e78727ee592b260606d',
    messagingSenderId: '156767151896',
    projectId: 'golftour-aa',
    authDomain: 'golftour-aa.firebaseapp.com',
    databaseURL: "https://golftour-aa-default-rtdb.europe-west1.firebasedatabase.app",
    storageBucket: 'golftour-aa.appspot.com',
    measurementId: 'G-N7WDEVY809',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHG0APspT3kS69mFPzHA336CltgXvj83M',
    appId: '1:156767151896:android:842faa7a2b6907f360606d',
    messagingSenderId: '156767151896',
    projectId: 'golftour-aa',
    storageBucket: 'golftour-aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtJcRafnvw5WTBF_3JaDZ9sbHH43xOjIo',
    appId: '1:156767151896:ios:c495b179211e813860606d',
    messagingSenderId: '156767151896',
    projectId: 'golftour-aa',
    storageBucket: 'golftour-aa.appspot.com',
    iosClientId: '156767151896-5jvfnm37r1ne0eu5cqpkej9fs73nkc22.apps.googleusercontent.com',
    iosBundleId: 'com.example.golfTour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtJcRafnvw5WTBF_3JaDZ9sbHH43xOjIo',
    appId: '1:156767151896:ios:c495b179211e813860606d',
    messagingSenderId: '156767151896',
    projectId: 'golftour-aa',
    storageBucket: 'golftour-aa.appspot.com',
    iosClientId: '156767151896-5jvfnm37r1ne0eu5cqpkej9fs73nkc22.apps.googleusercontent.com',
    iosBundleId: 'com.example.golfTour',
  );
}
